services:
  nginx-frontend:
    image: nginx
    build: ./nginx-frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - app

  api:
    build: ./api
    expose:
      - 5000
    deploy:
      replicas: 2

  app:
    build: ./app
    expose:
      - 5173
